using System;
using System.Collections.Generic;
using System.IO;

using NUnit.Framework;

using SandBeige.MediaBox.Library.Video;

namespace SandBeige.MediaBox.Library.Tests.Video {
	[TestFixture]
	internal class FFmpegTest {
		private static string _testDataDir;

		[SetUp]
		public void SetUp() {
			_testDataDir = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"TestData\");
		}

		[Test]
		public void Extract() {
			var ffmpeg = new FFmpeg(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"Externals\ffmpeg"));
			var path = Path.Combine(_testDataDir, "video1.mov");
			var meta = ffmpeg.ExtractMetadata(path);
			meta.Formats.Is(new Dictionary<string, string>() {
				{"filename", path},
				{"nb_streams","4"},
				{"nb_programs","0"},
				{"format_name","mov,mp4,m4a,3gp,3g2,mj2"},
				{"format_long_name","QuickTime / MOV"},
				{"start_time","0.000000"},
				{"duration","5.093333"},
				{"size","16398406"},
				{"bit_rate","25756660"},
				{"probe_score","100"},
				{"TAG:major_brand","qt"},
				{"TAG:minor_version","0"},
				{"TAG:compatible_brands","qt"},
				{"TAG:creation_time","2019-01-24T12:37:03.000000Z"},
				{"TAG:com.apple.quicktime.location.ISO6709","+34.9377+135.9119+088.072/"},
				{"TAG:com.apple.quicktime.make","Apple"},
				{"TAG:com.apple.quicktime.model","iPhone 6s"},
				{"TAG:com.apple.quicktime.software","11.3.1"},
				{"TAG:com.apple.quicktime.creationdate","2018-05-19T11:53:45+0900"}
			});

			meta.Streams.Is(new Dictionary<string, string>() {
				{"index", "0"},
				{"codec_name", "h264"},
				{"codec_long_name", "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10"},
				{"profile", "High"},
				{"codec_type", "video"},
				{"codec_time_base", "11/1250"},
				{"codec_tag_string", "avc1"},
				{"codec_tag", "0x31637661"},
				{"width", "1920"},
				{"height", "1080"},
				{"coded_width", "1920"},
				{"coded_height", "1088"},
				{"has_b_frames", "0"},
				{"sample_aspect_ratio", "N/A"},
				{"display_aspect_ratio", "N/A"},
				{"pix_fmt", "yuv420p"},
				{"level", "42"},
				{"color_range", "tv"},
				{"color_space", "bt709"},
				{"color_transfer", "bt709"},
				{"color_primaries", "bt709"},
				{"chroma_location", "left"},
				{"field_order", "unknown"},
				{"timecode", "N/A"},
				{"refs", "1"},
				{"is_avc", "true"},
				{"nal_length_size", "4"},
				{"id", "N/A"},
				{"r_frame_rate", "60000/1001"},
				{"avg_frame_rate", "625/11"},
				{"time_base", "1/600"},
				{"start_pts", "0"},
				{"start_time", "0.000000"},
				{"duration_ts", "3056"},
				{"duration", "5.093333"},
				{"bit_rate", "22834734"},
				{"max_bit_rate", "N/A"},
				{"bits_per_raw_sample", "8"},
				{"nb_frames", "325"},
				{"nb_read_frames", "N/A"},
				{"nb_read_packets", "N/A"},
				{"DISPOSITION:default", "1"},
				{"DISPOSITION:dub", "0"},
				{"DISPOSITION:original", "0"},
				{"DISPOSITION:comment", "0"},
				{"DISPOSITION:lyrics", "0"},
				{"DISPOSITION:karaoke", "0"},
				{"DISPOSITION:forced", "0"},
				{"DISPOSITION:hearing_impaired", "0"},
				{"DISPOSITION:visual_impaired", "0"},
				{"DISPOSITION:clean_effects", "0"},
				{"DISPOSITION:attached_pic", "0"},
				{"DISPOSITION:timed_thumbnails", "0"},
				{"TAG:creation_time", "2019-01-24T12:37:03.000000Z"},
				{"TAG:language", "und"},
				{"TAG:handler_name", "Core Media Video"},
				{"TAG:encoder", "H.264"}
			}, new Dictionary<string, string>() {
				{"index", "1"},
				{"codec_name", "aac"},
				{"codec_long_name", "AAC (Advanced Audio Coding)"},
				{"profile", "LC"},
				{"codec_type", "audio"},
				{"codec_time_base", "1/44100"},
				{"codec_tag_string", "mp4a"},
				{"codec_tag", "0x6134706d"},
				{"sample_fmt", "fltp"},
				{"sample_rate", "44100"},
				{"channels", "1"},
				{"channel_layout", "mono"},
				{"bits_per_sample", "0"},
				{"id", "N/A"},
				{"r_frame_rate", "0/0"},
				{"avg_frame_rate", "0/0"},
				{"time_base", "1/44100"},
				{"start_pts", "0"},
				{"start_time", "0.000000"},
				{"duration_ts", "224616"},
				{"duration", "5.093333"},
				{"bit_rate", "100122"},
				{"max_bit_rate", "96000"},
				{"bits_per_raw_sample", "N/A"},
				{"nb_frames", "223"},
				{"nb_read_frames", "N/A"},
				{"nb_read_packets", "N/A"},
				{"DISPOSITION:default", "1"},
				{"DISPOSITION:dub", "0"},
				{"DISPOSITION:original", "0"},
				{"DISPOSITION:comment", "0"},
				{"DISPOSITION:lyrics", "0"},
				{"DISPOSITION:karaoke", "0"},
				{"DISPOSITION:forced", "0"},
				{"DISPOSITION:hearing_impaired", "0"},
				{"DISPOSITION:visual_impaired", "0"},
				{"DISPOSITION:clean_effects", "0"},
				{"DISPOSITION:attached_pic", "0"},
				{"DISPOSITION:timed_thumbnails", "0"},
				{"TAG:creation_time", "2019-01-24T12:37:03.000000Z"},
				{"TAG:language", "und"},
				{"TAG:handler_name", "Core Media Audio"}
			}, new Dictionary<string, string>() {
				{"index", "2"},
				{"codec_name", "unknown"},
				{"codec_long_name", "unknown"},
				{"profile", "unknown"},
				{"codec_type", "data"},
				{"codec_tag_string", "mebx"},
				{"codec_tag", "0x7862656d"},
				{"id", "N/A"},
				{"r_frame_rate", "0/0"},
				{"avg_frame_rate", "0/0"},
				{"time_base", "1/600"},
				{"start_pts", "0"},
				{"start_time", "0.000000"},
				{"duration_ts", "3056"},
				{"duration", "5.093333"},
				{"bit_rate", "N/A"},
				{"max_bit_rate", "N/A"},
				{"bits_per_raw_sample", "N/A"},
				{"nb_frames", "1"},
				{"nb_read_frames", "N/A"},
				{"nb_read_packets", "N/A"},
				{"DISPOSITION:default", "1"},
				{"DISPOSITION:dub", "0"},
				{"DISPOSITION:original", "0"},
				{"DISPOSITION:comment", "0"},
				{"DISPOSITION:lyrics", "0"},
				{"DISPOSITION:karaoke", "0"},
				{"DISPOSITION:forced", "0"},
				{"DISPOSITION:hearing_impaired", "0"},
				{"DISPOSITION:visual_impaired", "0"},
				{"DISPOSITION:clean_effects", "0"},
				{"DISPOSITION:attached_pic", "0"},
				{"DISPOSITION:timed_thumbnails", "0"},
				{"TAG:creation_time", "2019-01-24T12:37:03.000000Z"},
				{"TAG:language", "und"},
				{"TAG:handler_name", "Core Media Metadata"}
			}, new Dictionary<string, string>() {
				{"index", "3"},
				{"codec_name", "unknown"},
				{"codec_long_name", "unknown"},
				{"profile", "unknown"},
				{"codec_type", "data"},
				{"codec_tag_string", "mebx"},
				{"codec_tag", "0x7862656d"},
				{"id", "N/A"},
				{"r_frame_rate", "0/0"},
				{"avg_frame_rate", "0/0"},
				{"time_base", "1/600"},
				{"start_pts", "0"},
				{"start_time", "0.000000"},
				{"duration_ts", "3056"},
				{"duration", "5.093333"},
				{"bit_rate", "N/A"},
				{"max_bit_rate", "N/A"},
				{"bits_per_raw_sample", "N/A"},
				{"nb_frames", "1"},
				{"nb_read_frames", "N/A"},
				{"nb_read_packets", "N/A"},
				{"DISPOSITION:default", "1"},
				{"DISPOSITION:dub", "0"},
				{"DISPOSITION:original", "0"},
				{"DISPOSITION:comment", "0"},
				{"DISPOSITION:lyrics", "0"},
				{"DISPOSITION:karaoke", "0"},
				{"DISPOSITION:forced", "0"},
				{"DISPOSITION:hearing_impaired", "0"},
				{"DISPOSITION:visual_impaired", "0"},
				{"DISPOSITION:clean_effects", "0"},
				{"DISPOSITION:attached_pic", "0"},
				{"DISPOSITION:timed_thumbnails", "0"},
				{"TAG:creation_time", "2019-01-24T12:37:03.000000Z"},
				{"TAG:language", "und"},
				{"TAG:handler_name", "Core Media Metadata"}
			});

			meta.Duration.Is(5.093333);
		}
	}
}