using System;
using System.IO;
using System.Linq;

using FluentAssertions;

using NUnit.Framework;

using SandBeige.MediaBox.Composition.Objects;
using SandBeige.MediaBox.Library.Video;
using SandBeige.MediaBox.TestUtilities;

namespace SandBeige.MediaBox.Library.Tests.Video {
	[TestFixture]
	internal class FfmpegTest : TestClassBase {
		[Test]
		public void Extract() {
			var ffmpeg = new Ffmpeg(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"Externals\ffmpeg"));
			var path = this.TestFiles.Video1Mov.FilePath;
			var meta = ffmpeg.ExtractMetadata(path);
			meta.Formats.Should().Equal(new Attributes<string> {
				{"filename",path},
				{"nb_streams","4"},
				{"nb_programs","0"},
				{"format_name","mov,mp4,m4a,3gp,3g2,mj2"},
				{"format_long_name","QuickTime / MOV"},
				{"start_time","0.000000"},
				{"duration","0.083333"},
				{"size","12117"},
				{"bit_rate","1163236"},
				{"probe_score","100"},
				{"TAG:major_brand","qt"},
				{"TAG:minor_version","0"},
				{"TAG:compatible_brands","qt"},
				{"TAG:creation_time","2019-05-12T08:35:25.000000Z"},
				{"TAG:com.apple.quicktime.location.ISO6709","+35.6896+139.6916+161.155/"},
				{"TAG:com.apple.quicktime.make","Apple"},
				{"TAG:com.apple.quicktime.model","iPhone XS"},
				{"TAG:com.apple.quicktime.software","12.2"},
				{"TAG:com.apple.quicktime.creationdate","2019-05-12T17:35:25+0900"},
			});

			meta.Streams.Should().HaveCount(4);
			meta.Streams.ToArray()[0].Should().Equal(new Attributes<string>() {
				{"index","0"},
				{"codec_name","hevc"},
				{"codec_long_name","H.265 / HEVC (High Efficiency Video Coding)"},
				{"profile","Main"},
				{"codec_type","video"},
				{"codec_time_base","1/24"},
				{"codec_tag_string","hvc1"},
				{"codec_tag","0x31637668"},
				{"width","1280"},
				{"height","720"},
				{"coded_width","1280"},
				{"coded_height","720"},
				{"has_b_frames","2"},
				{"sample_aspect_ratio","N/A"},
				{"display_aspect_ratio","N/A"},
				{"pix_fmt","yuv420p"},
				{"level","93"},
				{"color_range","tv"},
				{"color_space","bt709"},
				{"color_transfer","bt709"},
				{"color_primaries","bt709"},
				{"chroma_location","unspecified"},
				{"field_order","unknown"},
				{"timecode","N/A"},
				{"refs","1"},
				{"id","N/A"},
				{"r_frame_rate","24/1"},
				{"avg_frame_rate","24/1"},
				{"time_base","1/600"},
				{"start_pts","0"},
				{"start_time","0.000000"},
				{"duration_ts","50"},
				{"duration","0.083333"},
				{"bit_rate","312096"},
				{"max_bit_rate","N/A"},
				{"bits_per_raw_sample","N/A"},
				{"nb_frames","2"},
				{"nb_read_frames","N/A"},
				{"nb_read_packets","N/A"},
				{"DISPOSITION:default","1"},
				{"DISPOSITION:dub","0"},
				{"DISPOSITION:original","0"},
				{"DISPOSITION:comment","0"},
				{"DISPOSITION:lyrics","0"},
				{"DISPOSITION:karaoke","0"},
				{"DISPOSITION:forced","0"},
				{"DISPOSITION:hearing_impaired","0"},
				{"DISPOSITION:visual_impaired","0"},
				{"DISPOSITION:clean_effects","0"},
				{"DISPOSITION:attached_pic","0"},
				{"DISPOSITION:timed_thumbnails","0"},
				{"TAG:rotate","90"},
				{"TAG:creation_time","2019-05-12T08:35:25.000000Z"},
				{"TAG:language","und"},
				{"TAG:handler_name","Core Media Video"},
				{"TAG:encoder","HEVC"}
			});
			meta.Streams.ToArray()[1].Should().Equal(new Attributes<string>() {
				{"index","1"},
				{"codec_name","aac"},
				{"codec_long_name","AAC (Advanced Audio Coding)"},
				{"profile","LC"},
				{"codec_type","audio"},
				{"codec_time_base","1/44100"},
				{"codec_tag_string","mp4a"},
				{"codec_tag","0x6134706d"},
				{"sample_fmt","fltp"},
				{"sample_rate","44100"},
				{"channels","2"},
				{"channel_layout","stereo"},
				{"bits_per_sample","0"},
				{"id","N/A"},
				{"r_frame_rate","0/0"},
				{"avg_frame_rate","0/0"},
				{"time_base","1/44100"},
				{"start_pts","0"},
				{"start_time","0.000000"},
				{"duration_ts","3675"},
				{"duration","0.083333"},
				{"bit_rate","114778"},
				{"max_bit_rate","192000"},
				{"bits_per_raw_sample","N/A"},
				{"nb_frames","7"},
				{"nb_read_frames","N/A"},
				{"nb_read_packets","N/A"},
				{"DISPOSITION:default","1"},
				{"DISPOSITION:dub","0"},
				{"DISPOSITION:original","0"},
				{"DISPOSITION:comment","0"},
				{"DISPOSITION:lyrics","0"},
				{"DISPOSITION:karaoke","0"},
				{"DISPOSITION:forced","0"},
				{"DISPOSITION:hearing_impaired","0"},
				{"DISPOSITION:visual_impaired","0"},
				{"DISPOSITION:clean_effects","0"},
				{"DISPOSITION:attached_pic","0"},
				{"DISPOSITION:timed_thumbnails","0"},
				{"TAG:creation_time","2019-05-12T08:35:25.000000Z"},
				{"TAG:language","und"},
				{"TAG:handler_name","Core Media Audio"}
			});
			meta.Streams.ToArray()[2].Should().Equal(new Attributes<string>() {
				{"index","2"},
				{"codec_name","unknown"},
				{"codec_long_name","unknown"},
				{"profile","unknown"},
				{"codec_type","data"},
				{"codec_tag_string","mebx"},
				{"codec_tag","0x7862656d"},
				{"id","N/A"},
				{"r_frame_rate","0/0"},
				{"avg_frame_rate","0/0"},
				{"time_base","1/600"},
				{"start_pts","0"},
				{"start_time","0.000000"},
				{"duration_ts","50"},
				{"duration","0.083333"},
				{"bit_rate","768"},
				{"max_bit_rate","N/A"},
				{"bits_per_raw_sample","N/A"},
				{"nb_frames","1"},
				{"nb_read_frames","N/A"},
				{"nb_read_packets","N/A"},
				{"DISPOSITION:default","1"},
				{"DISPOSITION:dub","0"},
				{"DISPOSITION:original","0"},
				{"DISPOSITION:comment","0"},
				{"DISPOSITION:lyrics","0"},
				{"DISPOSITION:karaoke","0"},
				{"DISPOSITION:forced","0"},
				{"DISPOSITION:hearing_impaired","0"},
				{"DISPOSITION:visual_impaired","0"},
				{"DISPOSITION:clean_effects","0"},
				{"DISPOSITION:attached_pic","0"},
				{"DISPOSITION:timed_thumbnails","0"},
				{"TAG:creation_time","2019-05-12T08:35:25.000000Z"},
				{"TAG:language","und"},
				{"TAG:handler_name","Core Media Metadata"}
			});
			meta.Streams.ToArray()[3].Should().Equal(new Attributes<string>() {
				{"index","3"},
				{"codec_name","unknown"},
				{"codec_long_name","unknown"},
				{"profile","unknown"},
				{"codec_type","data"},
				{"codec_tag_string","mebx"},
				{"codec_tag","0x7862656d"},
				{"id","N/A"},
				{"r_frame_rate","0/0"},
				{"avg_frame_rate","0/0"},
				{"time_base","1/600"},
				{"start_pts","0"},
				{"start_time","0.000000"},
				{"duration_ts","50"},
				{"duration","0.083333"},
				{"bit_rate","960"},
				{"max_bit_rate","N/A"},
				{"bits_per_raw_sample","N/A"},
				{"nb_frames","1"},
				{"nb_read_frames","N/A"},
				{"nb_read_packets","N/A"},
				{"DISPOSITION:default","1"},
				{"DISPOSITION:dub","0"},
				{"DISPOSITION:original","0"},
				{"DISPOSITION:comment","0"},
				{"DISPOSITION:lyrics","0"},
				{"DISPOSITION:karaoke","0"},
				{"DISPOSITION:forced","0"},
				{"DISPOSITION:hearing_impaired","0"},
				{"DISPOSITION:visual_impaired","0"},
				{"DISPOSITION:clean_effects","0"},
				{"DISPOSITION:attached_pic","0"},
				{"DISPOSITION:timed_thumbnails","0"},
				{"TAG:creation_time","2019-05-12T08:35:25.000000Z"},
				{"TAG:language","und"},
				{"TAG:handler_name","Core Media Metadata"}
			});

			meta.Duration.Should().Be(0.083333);
		}
	}
}